[book]
title = "Kaen-Coon AI Cluster Documentation"
description = "Documentation for Using Kaen-Coon AI Cluster, College of Computing, Khon Kaen University"
authors = ["Napat Srichan"]
language = "en"
